### ISSUE TITLE
建立起始專案

### ISSUE THREAD

**Issue by Kahoulam** [PetNi-App/Blog#4]
1.  - [x] repository 命名
1. - [x] 建立 flutter repository
2. - [x] commit default flutter project

**Comment by Kahoulam** [comment]
@neslxzhen  
 repository name 直接叫 "APP" , 或有其他想法嗎?

**Comment by twkevinzhang** [comment]
> @neslxzhen repository name 直接叫 "APP" , 或有其他想法嗎?

approve.
你建完直接 close issue.
